Agriculture_Seeds_Sandeep/Controllers/AgricultureCropsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Agriculture_Seeds_Sandeep.Models;

namespace Agriculture_Seeds_Sandeep.Controllers
{
    [Authorize]
    public class AgricultureCropsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: AgricultureCrops
        public ActionResult Index()
        {
            return View(db.AgricultureCrops.ToList());
        }

        // GET: AgricultureCrops/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AgricultureCrop agricultureCrop = db.AgricultureCrops.Find(id);
            if (agricultureCrop == null)
            {
                return HttpNotFound();
            }
            return View(agricultureCrop);
        }

        // GET: AgricultureCrops/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AgricultureCrops/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,CropName")] AgricultureCrop agricultureCrop)
        {
            if (ModelState.IsValid)
            {
                db.AgricultureCrops.Add(agricultureCrop);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(agricultureCrop);
        }

        // GET: AgricultureCrops/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AgricultureCrop agricultureCrop = db.AgricultureCrops.Find(id);
            if (agricultureCrop == null)
            {
                return HttpNotFound();
            }
            return View(agricultureCrop);
        }

        // POST: AgricultureCrops/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,CropName")] AgricultureCrop agricultureCrop)
        {
            if (ModelState.IsValid)
            {
                db.Entry(agricultureCrop).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(agricultureCrop);
        }

        // GET: AgricultureCrops/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AgricultureCrop agricultureCrop = db.AgricultureCrops.Find(id);
            if (agricultureCrop == null)
            {
                return HttpNotFound();
            }
            return View(agricultureCrop);
        }

        // POST: AgricultureCrops/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AgricultureCrop agricultureCrop = db.AgricultureCrops.Find(id);
            db.AgricultureCrops.Remove(agricultureCrop);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Agriculture_Seeds_Sandeep/Controllers/AgricultureStoresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Agriculture_Seeds_Sandeep.Models;

namespace Agriculture_Seeds_Sandeep.Controllers
{
    [Authorize]
    public class AgricultureStoresController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: AgricultureStores
        public ActionResult Index()
        {
            var agricultureStores = db.AgricultureStores.Include(a => a.AgricultureCropVariety);
            return View(agricultureStores.ToList());
        }

        // GET: AgricultureStores/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AgricultureStore agricultureStore = db.AgricultureStores.Find(id);
            if (agricultureStore == null)
            {
                return HttpNotFound();
            }
            return View(agricultureStore);
        }

        // GET: AgricultureStores/Create
        public ActionResult Create()
        {
            ViewBag.AgricultureCropVarietyID = new SelectList(db.AgricultureCropVarieties, "ID", "VarietyName");
            return View();
        }

        // POST: AgricultureStores/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,AgricultureCropVarietyID,Quantity,NoofBags")] AgricultureStore agricultureStore)
        {
            if (ModelState.IsValid)
            {
                db.AgricultureStores.Add(agricultureStore);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AgricultureCropVarietyID = new SelectList(db.AgricultureCropVarieties, "ID", "VarietyName", agricultureStore.AgricultureCropVarietyID);
            return View(agricultureStore);
        }

        // GET: AgricultureStores/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AgricultureStore agricultureStore = db.AgricultureStores.Find(id);
            if (agricultureStore == null)
            {
                return HttpNotFound();
            }
            ViewBag.AgricultureCropVarietyID = new SelectList(db.AgricultureCropVarieties, "ID", "VarietyName", agricultureStore.AgricultureCropVarietyID);
            return View(agricultureStore);
        }

        // POST: AgricultureStores/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,AgricultureCropVarietyID,Quantity,NoofBags")] AgricultureStore agricultureStore)
        {
            if (ModelState.IsValid)
            {
                db.Entry(agricultureStore).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AgricultureCropVarietyID = new SelectList(db.AgricultureCropVarieties, "ID", "VarietyName", agricultureStore.AgricultureCropVarietyID);
            return View(agricultureStore);
        }

        // GET: AgricultureStores/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AgricultureStore agricultureStore = db.AgricultureStores.Find(id);
            if (agricultureStore == null)
            {
                return HttpNotFound();
            }
            return View(agricultureStore);
        }

        // POST: AgricultureStores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AgricultureStore agricultureStore = db.AgricultureStores.Find(id);
            db.AgricultureStores.Remove(agricultureStore);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Agriculture_Seeds_Sandeep/Controllers/BankPaymentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Agriculture_Seeds_Sandeep.Models;

namespace Agriculture_Seeds_Sandeep.Controllers
{
    [Authorize]
    public class BankPaymentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: BankPayments
        public ActionResult Index()
        {
            return View(db.BankPayments.ToList());
        }

        // GET: BankPayments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BankPayment bankPayment = db.BankPayments.Find(id);
            if (bankPayment == null)
            {
                return HttpNotFound();
            }
            return View(bankPayment);
        }

        // GET: BankPayments/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: BankPayments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,TransactionDate,TransactionNumber,AmountReceived")] BankPayment bankPayment)
        {
            if (ModelState.IsValid)
            {
                db.BankPayments.Add(bankPayment);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(bankPayment);
        }

        // GET: BankPayments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BankPayment bankPayment = db.BankPayments.Find(id);
            if (bankPayment == null)
            {
                return HttpNotFound();
            }
            return View(bankPayment);
        }

        // POST: BankPayments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,TransactionDate,TransactionNumber,AmountReceived")] BankPayment bankPayment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bankPayment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(bankPayment);
        }

        // GET: BankPayments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BankPayment bankPayment = db.BankPayments.Find(id);
            if (bankPayment == null)
            {
                return HttpNotFound();
            }
            return View(bankPayment);
        }

        // POST: BankPayments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BankPayment bankPayment = db.BankPayments.Find(id);
            db.BankPayments.Remove(bankPayment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Agriculture_Seeds_Sandeep/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Agriculture_Seeds_Sandeep.Models;

namespace Agriculture_Seeds_Sandeep.Controllers
{
    [Authorize]
    public class CustomersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Customers
        public ActionResult Index()
        {
            return View(db.Customers.ToList());
        }

        // GET: Customers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // GET: Customers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Customers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,CustomerName,PhoneNumber,Address")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Customers.Add(customer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(customer);
        }

        // GET: Customers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,CustomerName,PhoneNumber,Address")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(customer);
        }

        // GET: Customers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Customer customer = db.Customers.Find(id);
            db.Customers.Remove(customer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Agriculture_Seeds_Sandeep/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <title>Agriculture_firm a Agriculture Category Flat Bootstarp Resposive Website Template | Home :: w3layouts</title>
    <link href="~/Content/agriculture_firm-web/web/css/style.css" rel="stylesheet" />
    <link href="~/Content/agriculture_firm-web/web/css/bootstrap.css" rel="stylesheet" />
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,100italic,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css'>
    <!-- js -->
    <script src="~/Content/agriculture_firm-web/web/js/jquery.min.js"></script>
    <!-- //js -->
    <!-- for-mobile-apps -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Agriculture_firm Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
		Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    <script type="application/x-javascript">
        addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
                       function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- //for-mobile-apps -->
    <!-- start-smoth-scrolling -->
    <script type="text/javascript" src="~/Content/agriculture_firm-web/web/js/move-top.js"></script>
    <script type="text/javascript" src="~/Content/agriculture_firm-web/web/js/easing.js"></script>
    <script type="text/javascript">
        jQuery(document).ready(function ($) {
            $(".scroll").click(function (event) {
                event.preventDefault();
                $('html,body').animate({ scrollTop: $(this.hash).offset().top }, 1000);
            });
        });
    </script>
    <!-- start-smoth-scrolling -->
</head>

<body>
    <!-- banner -->
    <div id="home" class="banner">
        <div class="container">
            <div class="navi">
                <div class="head-logo">
                    <img src="~/Content/agriculture_firm-web/web/images/logo.png" />
                    <span style="margin-right:500px"> @Html.Partial("_LoginPartial")</span>
                </div>
                <div class="banner-nav">
                    <span class="menu"><img src="~/Content/agriculture_firm-web/web/images/menu.png" alt=" " /></span>
                    <nav class="cl-effect-3">
                        <ul class="nav1">
                            <li><a href="@Url.Action("Index", "AgricultureCrops")">Crop</a></li>
                            <li><a href="@Url.Action("Index", "AgricultureCropVarieties")"></i> Crop Variety</a></li>
                            <li><a href="@Url.Action("Index", "AgricultureCropRates")">Crop Rate</a></li>
                            <li><a href="@Url.Action("Index", "AgricultureStores")"> Store</a></li>
                            <li><a href="@Url.Action("Index", "Customers")">Customer</a></li>
                            <li><a href="@Url.Action("Index", "AgricultureSeedSellings")"> Selling</a></li>
                            <li><a href="@Url.Action("Index", "BankPayments")">Payment</a></li>
                            @*<li class="active"><a href="#home" class="scroll">Home</a></li>
                                <li><a href="#about" class="scroll">ABOUT</a></li>
                                <li><a href="#products" class="scroll">PRODUCTS</a></li>
                                <li><a href="#pricing" class="scroll">PRICING</a></li>
                                <li><a href="#contact" class="scroll">CONTACT</a></li>*@
                        </ul>
                    </nav>
                </div>
                <div class="clearfix"> </div>
            </div>
            <!-- script for menu -->
            <script>
                $("span.menu").click(function () {
                    $("ul.nav1").slideToggle(300, function () {
                        // Animation complete.
                    });
                });
            </script>
            <!-- //script for menu -->
            <div class="banner-info">
                <div class="banner-info-left">
                    <h3>OUR MISSION IS TO MAKE YOUR <span> BUSINESS GROW</span></h3>
                    <p>Donec rutrum congue leo eget malesuada<span>Curabitur non nulla sit amet.</span></p>
                    <div class="start">
                        <a href="#">Learn More...</a>
                    </div>
                </div>
                <div class="banner-info-right">
                    <div class="banner-info-fig">
                        <a href="~/Content/agriculture_firm-web/web/images/4.jpg" class="b-link-stripe b-animate-go   swipebox" title="">
                            <img class="img-responsive" src="~/Content/agriculture_firm-web/web/images/4-.jpg" />
                        </a>
                    </div>
                    <div class="banner-info-fig">
                        <a href="~/Content/agriculture_firm-web/web/images/5.jpg" class="b-link-stripe b-animate-go   swipebox" title="">
                            <img class="img-responsive" src="~/Content/agriculture_firm-web/web/images/5-.jpg" />
                        </a>
                    </div>
                    <div class="clearfix"> </div>
                    <div class="banner-info-fig">
                        <a href="~/Content/agriculture_firm-web/web/images/6.jpg" class="b-link-stripe b-animate-go   swipebox" title="">
                            <img class="img-responsive" src="~/Content/agriculture_firm-web/web/images/6-.jpg" />
                        </a>
                    </div>
                    <div class="banner-info-fig">
                        <a href="images/7.jpg" class="b-link-stripe b-animate-go   swipebox" title="">
                            <img class="img-responsive" src="images/7-.jpg" />
                        </a>
                    </div>
                    <div class="clearfix"> </div>
                </div>
                <div class="clearfix"> </div>
            </div>
            <link rel="stylesheet" href="css/swipebox.css">
            <script src="js/jquery.swipebox.min.js"></script>
            <script type="text/javascript">
                jQuery(function ($) {
                    $(".swipebox").swipebox();
                });
            </script>
            <!-- Portfolio Ends Here -->
            <script type="text/javascript" src="~/Content/agriculture_firm-web/web/js/jquery.mixitup.min.js"></script>
            <script type="text/javascript">
                $(function () {
                    var filterList = {
                        init: function () {
                            // MixItUp plugin
                            // http://mixitup.io
                            $('#portfoliolist').mixitup({
                                targetSelector: '.portfolio',
                                filterSelector: '.filter',
                                effects: ['fade'],
                                easing: 'snap',
                                // call the hover effect
                                onMixEnd: filterList.hoverEffect()
                            });
                        },
                        hoverEffect: function () {
                            // Simple parallax effect
                            $('#portfoliolist .portfolio').hover(
                                function () {
                                    $(this).find('.label').stop().animate({ bottom: 0 }, 200, 'easeOutQuad');
                                    $(this).find('img').stop().animate({ top: -30 }, 500, 'easeOutQuad');
                                },
                                function () {
                                    $(this).find('.label').stop().animate({ bottom: -40 }, 200, 'easeInQuad');
                                    $(this).find('img').stop().animate({ top: 0 }, 300, 'easeOutQuad');
                                }
                            );
                        }
                    };
                    // Run the show!
                    filterList.init();
                });
            </script>
        </div>
    </div>
    <!-- //banner -->
    <!-- banner-bottom -->
    <div class="banner-bottom">
        <div class="container">
            <!-- Slider-starts-Here -->
            <script src="~/Content/agriculture_firm-web/web/js/responsiveslides.min.js"></script>
            <script>
                // You can also use "$(window).load(function() {"
                $(function () {
                    // Slideshow 4
                    $("#slider3").responsiveSlides({
                        auto: true,
                        pager: true,
                        nav: false,
                        speed: 500,
                        namespace: "callbacks",
                        before: function () {
                            $('.events').append("<li>before event fired.</li>");
                        },
                        after: function () {
                            $('.events').append("<li>after event fired.</li>");
                        }
                    });

                });
            </script>
            <!--//End-slider-script -->
            <div id="top" class="callbacks_container">
                @RenderBody()
            </div>
        </div>
    </div>
    <!-- //banner-bottom -->
    <!-- footer -->
    <div class="footer">
        <div class="container">
            <div class="temp">
                <p>Design by <a href="http://w3layouts.com/">w3layouts</a></p>
            </div>
            <div class="footer-icons">

            </div>
            <div class="clearfix"> </div>
        </div>
    </div>
    <!-- //footer -->
    <!-- here stars scrolling icon -->
    <script type="text/javascript">
        $(document).ready(function () {
            /*
            var defaults = {
                    containerID: 'toTop', // fading element id
                containerHoverID: 'toTopHover', // fading element hover id
                scrollSpeed: 1200,
                easingType: 'linear'
                };
            */

            $().UItoTop({ easingType: 'easeOutQuart' });

        });
    </script>
    <!-- //here ends scrolling icon -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>